In [1]:
! pip install numpy

In [2]:
l = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9, 10]
]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]

In [3]:
import numpy

In [4]:
l = [1, 2, 3, 4, 5]
# convert list into numpy array
arr = numpy.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
# number of dimension of array
arr.ndim

1

In [7]:
arr2 = numpy.array(10)
print(arr2)
print(type(arr2))
print(arr2.ndim)

10
<class 'numpy.ndarray'>
0


In [8]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]

arr3 = numpy.array(l)
print(arr3)
print(type(arr3))
print(arr3.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


# 1D Array

In [9]:
a = 2
arr = numpy.array(a)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

2
<class 'numpy.ndarray'>
0
()


In [10]:
l = [1, 2, 3, 4]
arr1 = numpy.array(l)

print(arr1)
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)


In [11]:
arr1[2]

np.int64(3)

In [12]:
l = [1, 2, 3, 4]
arr1 = numpy.array(l, dtype = numpy.int32)

arr1[2]

np.int32(3)

In [13]:
l = [1, 2, 3, 4]
arr1 = numpy.array(l, dtype = numpy.float32)

arr1[2]

np.float32(3.0)

### 2-D Array

In [14]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]
arr2 = numpy.array(l)
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)


In [15]:
arr2[1][2]

np.int64(6)

In [16]:
arr2[1, 2]

np.int64(6)

### 3-D Array

In [17]:
l = [[
    [1, 2],
    [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]
arr3 = numpy.array(l)
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
3
(2, 2, 2)


In [18]:
arr3[1,0,1]

np.int64(6)

In [19]:
arr = numpy.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
arr.shape

(20,)

In [21]:
arr.reshape(1, 20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [22]:
arr.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
arr.reshape(2, 2, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [28]:
arr3 = arr.reshape(2, 2, 5)
arr3


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [30]:
arr3[1, 0, 3]

np.int64(13)

In [31]:
arr3[::, ::, 1:3:1]

array([[[ 1,  2],
        [ 6,  7]],

       [[11, 12],
        [16, 17]]])

In [32]:
arr3[::, 0, 1:3:1]

array([[ 1,  2],
       [11, 12]])

In [34]:
import numpy as np

In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

arr1 + arr2

array([11, 22, 33])

In [42]:
arr1 * arr2

array([10, 40, 90])

In [43]:
np.multiply(arr1, arr2)

array([10, 40, 90])

In [44]:
np.dot(arr1, arr2)

np.int64(140)

In [41]:
l1 = [1, 2, 3]
l2 = [10, 20, 30]
[ele1 + ele2 for ele1, ele2 in zip(l1, l2)]


[11, 22, 33]

In [46]:
arr3 = np.array([10, 100, 1000, 10000])
arr3

array([   10,   100,  1000, 10000])

In [48]:
np.log10(arr3)

array([1., 2., 3., 4.])

In [50]:
arr2 = np.arange(10).reshape((2, 5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Broadcasting

In [51]:
arr1 = np.arange(1, 7)
arr1

array([1, 2, 3, 4, 5, 6])

In [52]:
arr1 + 10

array([11, 12, 13, 14, 15, 16])

In [53]:
arr1 + np.array(10)

array([11, 12, 13, 14, 15, 16])

In [54]:
arr = np.arange(100).reshape((4, 5, 5))
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [55]:
arr.min()

np.int64(0)

In [57]:
arr.min(axis= 2)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [59]:
np.argmin(arr, axis = -1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])